# Generated by Django 3.2.25 on 2026-06-12 11:10

from django.db import migrations


def create_initial_goods_data(apps, schema_editor):
    """创建初始商品分类和商品数据，使项目 clone 后无需依赖预填充的数据库"""
    GoodsType = apps.get_model('goods', 'GoodsType')
    Goods = apps.get_model('goods', 'Goods')
    GoodsSKU = apps.get_model('goods', 'GoodsSKU')

    # 如果已存在数据则跳过（幂等性保证）
    if GoodsType.objects.exists():
        return

    # ========== 商品分类 ==========
    types = {
        'home': GoodsType.objects.create(
            name='家居家装', logo='home', image=''
        ),
        'beauty': GoodsType.objects.create(
            name='美妆护肤', logo='beauty', image='type/beauty.png'
        ),
        'health': GoodsType.objects.create(
            name='医疗保健', logo='health', image='type/health.png'
        ),
        'travel': GoodsType.objects.create(
            name='生活旅行', logo='travel', image='type/travel.png'
        ),
        'sport': GoodsType.objects.create(
            name='运动户外', logo='sport', image='type/sport.png'
        ),
        'computer': GoodsType.objects.create(
            name='电脑办公', logo='computer', image='type/computer.png'
        ),
    }

    # ========== 商品 SPU ==========
    goods_data = [
        # 家居家装 (type=home)
        ('简约北欧沙发', '<p>高密度回弹海绵，实木框架，透气棉麻面料</p>'),
        ('智能LED吸顶灯', '<p>高亮LED芯片，遥控调光调色，节能省电</p>'),
        ('天然乳胶枕', '<p>天然乳胶含量93%，透气防螨，柔软回弹</p>'),
        ('实木书柜', '<p>进口白橡木，环保水性漆，承重力强</p>'),
        # 美妆护肤 (type=beauty)
        ('保湿补水面膜', '<p>三重玻尿酸精华，深层补水锁水，轻薄服帖</p>'),
        ('防晒霜SPF50', '<p>轻薄不油腻，防水防汗，全波段防护</p>'),
        ('精华液', '<p>5%烟酰胺，淡化痘印，提亮肤色</p>'),
        ('口红套装', '<p>丝绒哑光质地，持久不脱色，显白百搭</p>'),
        # 医疗保健 (type=health)
        ('电子血压计', '<p>智能加压，大屏显示，语音播报，一键测量</p>'),
        ('维生素C片', '<p>天然针叶樱桃提取，每片含VC 500mg</p>'),
        ('医用口罩', '<p>三层防护，BFE≥95%，透气舒适</p>'),
        ('蛋白粉', '<p>进口乳清蛋白，低脂低糖，易吸收</p>'),
        # 生活旅行 (type=travel)
        ('旅行背包', '<p>防泼水面料，人体工学背负，多隔层收纳</p>'),
        ('保温杯', '<p>316不锈钢内胆，12小时保温，便携设计</p>'),
        ('旅行收纳套装', '<p>分类收纳，防水面料，轻便实用</p>'),
        ('自拍杆三脚架', '<p>360度旋转，伸缩自如，蓝牙遥控</p>'),
        # 运动户外 (type=sport)
        ('瑜伽垫', '<p>双面防滑，高密度NBR材质，柔软回弹</p>'),
        ('运动跑鞋', '<p>飞织网面，EVA缓震中底，防滑耐磨大底</p>'),
        ('运动水壶', '<p>食品级Tritan材质，防漏设计，单手开盖</p>'),
        ('跳绳', '<p>钢丝绳芯，PVC包裹，360度旋转轴承</p>'),
        # 电脑办公 (type=computer)
        ('机械键盘', '<p>Cherry MX红轴，RGB背光，全键无冲</p>'),
        ('无线鼠标', '<p>人体工学设计，静音按键，长续航</p>'),
        ('移动硬盘', '<p>高速传输，即插即用，防震抗摔</p>'),
        ('笔记本电脑支架', '<p>全铝合金材质，多角度调节，散热设计</p>'),
    ]
    goods_objs = {}
    for name, detail in goods_data:
        goods_objs[name] = Goods.objects.create(name=name, detail=detail)

    # ========== 商品 SKU ==========
    skus_data = [
        # 家居家装
        ('home', '简约北欧沙发', '北欧布艺沙发 三人位 深灰色', '高密度回弹海绵，实木框架，透气棉麻面料', '2899.00', '套', 'goods/简约北欧沙发.png', 200),
        ('home', '智能LED吸顶灯', '现代简约客厅吸顶灯 60W 三色调光', '高亮LED芯片，遥控调光调色，节能省电', '369.00', '个', 'goods/智能LED吸顶灯.png', 500),
        ('home', '天然乳胶枕', '泰国进口天然乳胶枕 人体工学护颈', '天然乳胶含量93%，透气防螨，柔软回弹', '199.00', '个', 'goods/天然乳胶枕.png', 800),
        ('home', '实木书柜', '北欧简约实木书架 四层开放式', '进口白橡木，环保水性漆，承重力强', '1599.00', '个', 'goods/实木书柜.png', 150),
        # 美妆护肤
        ('beauty', '保湿补水面膜', '玻尿酸深层补水面膜 10片装', '三重玻尿酸精华，深层补水锁水，轻薄服帖', '69.90', '盒', 'goods/保湿补水面膜.png', 2000),
        ('beauty', '防晒霜SPF50', '清爽水感防晒霜 SPF50+ PA++++', '轻薄不油腻，防水防汗，全波段防护', '129.00', '支', 'goods/防晒霜SPF50.png', 1500),
        ('beauty', '精华液', '烟酰胺亮肤精华液 30ml', '5%烟酰胺，淡化痘印，提亮肤色', '189.00', '瓶', 'goods/精华液.png', 1200),
        ('beauty', '口红套装', '丝绒哑光口红 六色套装', '丝绒哑光质地，持久不脱色，显白百搭', '259.00', '套', 'goods/口红套装.png', 600),
        # 医疗保健
        ('health', '电子血压计', '上臂式全自动电子血压计', '智能加压，大屏显示，语音播报，一键测量', '299.00', '台', 'goods/电子血压计.png', 400),
        ('health', '维生素C片', '天然维生素C咀嚼片 100片', '天然针叶樱桃提取，每片含VC 500mg', '89.00', '瓶', 'goods/维生素C片.png', 3000),
        ('health', '医用口罩', '一次性医用外科口罩 50只装', '三层防护，BFE≥95%，透气舒适', '29.90', '盒', 'goods/医用口罩.png', 5000),
        ('health', '蛋白粉', '乳清蛋白粉 增肌健身 900g', '进口乳清蛋白，低脂低糖，易吸收', '259.00', '罐', 'goods/蛋白粉.png', 800),
        # 生活旅行
        ('travel', '旅行背包', '大容量户外旅行背包 40L 防水', '防泼水面料，人体工学背负，多隔层收纳', '299.00', '个', 'goods/旅行背包.png', 600),
        ('travel', '保温杯', '不锈钢真空保温杯 500ml', '316不锈钢内胆，12小时保温，便携设计', '129.00', '个', 'goods/保温杯.png', 1500),
        ('travel', '旅行收纳套装', '旅行收纳袋六件套 防水', '分类收纳，防水面料，轻便实用', '49.90', '套', 'goods/旅行收纳套装.png', 2000),
        ('travel', '自拍杆三脚架', '蓝牙自拍杆三脚架 手机通用', '360度旋转，伸缩自如，蓝牙遥控', '79.00', '个', 'goods/自拍杆三脚架.png', 1000),
        # 运动户外
        ('sport', '瑜伽垫', '加厚防滑瑜伽垫 NBR材质 10mm', '双面防滑，高密度NBR材质，柔软回弹', '99.00', '条', 'goods/瑜伽垫.png', 1200),
        ('sport', '运动跑鞋', '轻便透气跑步鞋 网面减震', '飞织网面，EVA缓震中底，防滑耐磨大底', '459.00', '双', 'goods/运动跑鞋.png', 500),
        ('sport', '运动水壶', 'Tritan材质运动水壶 750ml', '食品级Tritan材质，防漏设计，单手开盖', '59.00', '个', 'goods/运动水壶.png', 1800),
        ('sport', '跳绳', '高速轴承跳绳 专业健身', '钢丝绳芯，PVC包裹，360度旋转轴承', '39.00', '根', 'goods/跳绳.png', 2500),
        # 电脑办公
        ('computer', '机械键盘', '机械键盘 红轴 87键 RGB背光', 'Cherry MX红轴，RGB背光，全键无冲', '399.00', '个', 'goods/机械键盘.png', 350),
        ('computer', '无线鼠标', '静音无线鼠标 双模蓝牙+2.4G', '人体工学设计，静音按键，长续航', '99.00', '个', 'goods/无线鼠标.png', 1000),
        ('computer', '移动硬盘', 'USB3.0移动硬盘 2TB 便携', '高速传输，即插即用，防震抗摔', '459.00', '个', 'goods/移动硬盘.png', 300),
        ('computer', '笔记本电脑支架', '铝合金笔记本支架 可升降', '全铝合金材质，多角度调节，散热设计', '159.00', '个', 'goods/笔记本电脑支架.png', 700),
    ]

    for type_key, goods_name, sku_name, desc, price, unite, image, stock in skus_data:
        GoodsSKU.objects.create(
            type=types[type_key],
            goods=goods_objs[goods_name],
            name=sku_name,
            desc=desc,
            price=price,
            unite=unite,
            image=image,
            stock=stock,
            status=1,
        )


def remove_goods_data(apps, schema_editor):
    """回滚时删除数据"""
    GoodsSKU = apps.get_model('goods', 'GoodsSKU')
    Goods = apps.get_model('goods', 'Goods')
    GoodsType = apps.get_model('goods', 'GoodsType')
    GoodsSKU.objects.all().delete()
    Goods.objects.all().delete()
    GoodsType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_goods_data, remove_goods_data),
    ]
