"""
Django settings for dailyfresh project.

Generated by 'django-admin startproject' using Django 1.8.2.
Updated for Django 3.2 compatibility.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sey57zv3960^vazw=$#gf!677#@d3(!5fpnl2jhj9)#s&%9ywq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce', # 富文本编辑器
    'haystack', # 全文检索框架
    'user', # 用户模块
    'goods', # 商品模块
    'cart', # 购物车模块
    'order', # 订单模块
)

# 中间件--生命周期方法
MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'dailyfresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dailyfresh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# 开发环境使用 SQLite（避免 MySQL 依赖）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# 原 MySQL 配置（生产环境使用）
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'dailyfresh',
#         'USER': 'root',
#         'PASSWORD': '123qwe',
#         'HOST': 'localhost',
#         'PORT': 3306,
#     }
# }

# Django认证系统使用的模型类
# 替换django默认账户
# python manage.py createsuperuser
AUTH_USER_MODEL = 'user.User'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# 指定收集静态文件的路径--nginx调度静态文件
# 使用命令： python manage.py collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

# 富文本编辑器配置
TINYMCE_DEFAULT_CONFIG = {
    'theme': 'advanced',
    'width': 600,
    'height': 400,
}

# 发送邮件配置（开发环境使用控制台后端）
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# smtp服务地址（生产环境使用）
# EMAIL_HOST = 'smtp.163.com'
# EMAIL_PORT = 25
# EMAIL_HOST_USER = 'hyw144@163.com'
# EMAIL_HOST_PASSWORD = 'huang123'
# EMAIL_FROM = 'python<hyw144@163.com>'

# Django的缓存配置（开发环境使用 fakeredis 模拟 Redis）
import fakeredis

class _StrRedisWrapper:
    """包装 fakeredis，自动将 bytes 转为 str，避免 b'1' 显示问题"""
    def __init__(self):
        self._r = fakeredis.FakeStrictRedis(decode_responses=True)

    def __getattr__(self, name):
        return getattr(self._r, name)

_fake_redis_instance = _StrRedisWrapper()

# 替换 django_redis.get_redis_connection，使其返回 fakeredis 实例
import django_redis
_original_get_redis_connection = django_redis.get_redis_connection

def _fake_get_redis_connection(alias='default', write=True):
    return _fake_redis_instance

django_redis.get_redis_connection = _fake_get_redis_connection

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

# 配置session存储
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# 配置登录URL地址
LOGIN_URL = '/user/login'

# 设置django的文件存储类（开发环境使用默认存储）
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# 原 FastDFS 文件存储配置（生产环境使用）
# DEFAULT_FILE_STORAGE = 'utils.fdfs.storage.FDFSStorage'
# FDFS_CLIENT_CONF = './utils/fdfs/client.conf'
# FDFS_URL = 'http://192.168.171.129:8888/'

# 自定义文件存储路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# 全文检索框架的配置（开发环境使用标准 whoosh 引擎）
HAYSTACK_CONNECTIONS = {
    'default': {
        #使用whoosh引擎
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        # 'ENGINE': 'haystack.backends.whoosh_cn_backend.WhooshEngine',  # 中文分词引擎(需配置jieba)
        #索引文件路径 存放索引目录
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}

#当添加、修改、删除数据时，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# Django 3.2 默认主键类型
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
